---
- name: Install pipx
  package:
    name: pipx
    state: present
  become: true

- name: Ensure pipx is in PATH
  shell: pipx ensurepath
  become: false
  changed_when: false

- name: Install pipx packages
  shell: pipx install {{ item }}
  loop: "{{ pipx_packages }}"
  become: false
  register: pipx_install_result
  changed_when: "'installed package' in pipx_install_result.stdout"
  failed_when: pipx_install_result.rc != 0 and 'already installed' not in pipx_install_result.stderr